### ISSUE TITLE
"f{BaseCliMediaApi.api_url_base}" ==> "f{ ==> f"{

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#20]
Hi Vivien.

I think there is still a little problem in de API.

http://192.168.178.7:7878f{BaseCliMediaApi.api_url_base}/movie/lookup: Failed to parse: http://192.168.178.7:7878f{BaseCliMediaApi.api_url_base}/movie/lookup

Traceback (most recent call last):
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/marco/Documents/GitHub/pixlovarr/./app/pixlovarr.py", line 1926, in downloadMovies
    self.findMedia(update, context, None, "movie", context.args)
  File "/Users/marco/Documents/GitHub/pixlovarr/./app/pixlovarr.py", line 2519, in findMedia
    media = self.radarr_node.lookup_movie(term=searchQuery)
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/pycliarr/api/radarr.py", line 119, in lookup_movie
    res = self.lookup_item(str(term))
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/pycliarr/api/base_media.py", line 120, in lookup_item
    return self.request_get(self.api_url_itemlookup, url_params=url_params)
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/pycliarr/api/base_api.py", line 96, in request_get
    return self.request("GET", path, url_params=url_params)
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/pycliarr/api/base_api.py", line 81, in request
    raise CliArrError(f"Error sending request {request_url}: {e}")
pycliarr.api.exceptions.CliArrError: Error sending request http://192.168.178.7:7878f{BaseCliMediaApi.api_url_base}/movie/lookup: Failed to parse: http://192.168.178.7:7878f{BaseCliMediaApi.api_url_base}/movie/lookup

**Comment by marc0janssen** [comment]
api_url_itemlookup = "f{BaseCliMediaApi.api_url_base}/movie/lookup"

Found it for you....

"f{ instead of f"{
