### ISSUE TITLE
pycliarr.api.exceptions.CliServerError:  404

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#22]
pycliarr.api.exceptions.CliServerError: Error from server http://192.168.178.7:8989/api/v3series/lookup, status: 404, msg: '{\n  "message": "NotFound"\n}'

I guess there is missing a "/" in the URL between "v3" and "Series"

Should be:

http://192.168.178.7:8989/api/v3/series/lookup

**Comment by marc0janssen** [comment]
Traceback (most recent call last):
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/marco/Documents/GitHub/pixlovarr/./app/pixlovarr.py", line 1685, in downloadSeries
    self.findMedia(update, context, None, "serie", context.args)
  File "/Users/marco/Documents/GitHub/pixlovarr/./app/pixlovarr.py", line 2516, in findMedia
    media = self.sonarr_node.lookup_serie(term=searchQuery)
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/pycliarr/api/sonarr.py", line 124, in lookup_serie
    res = self.lookup_item(str(term))
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/pycliarr/api/base_media.py", line 120, in lookup_item
    return self.request_get(self.api_url_itemlookup, url_params=url_params)
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/pycliarr/api/base_api.py", line 96, in request_get
    return self.request("GET", path, url_params=url_params)
  File "/Users/marco/Library/Python/3.9/lib/python/site-packages/pycliarr/api/base_api.py", line 83, in request
    raise CliServerError(
pycliarr.api.exceptions.CliServerError: Error from server http://192.168.178.7:8989/api/v3series/lookup, status: 404, msg: '{\n  "message": "NotFound"\n}'

**Comment by vche** [comment]
yes, and then if you fix that, the apiv3 added the language profile which is not implemented yet. will fix this

**Comment by marc0janssen** [comment]
Great.... no rush... main docker container is still running the previous pycliarr (.15) so I am still up ;-)

**Comment by marc0janssen** [comment]
404 is fixed.. Seem to work fine now. Merci!
